---
apiVersion: v1
kind: Namespace
metadata:
  name: raytest
  labels:
    opendatahub.io/dashboard: "true"
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: comprehensive-mixed
  namespace: raytest
  labels:
    controller-tools.k8s.io: "1.0"
spec:
  rayVersion: "2.47.1"
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
      block: "true"
    template:
      spec:
        containers:
          - name: ray-head
            image: quay.io/modh/ray@sha256:0d715f92570a2997381b7cafc0e224cfa25323f18b9545acfd23bc2b71576d06
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "1"
                memory: 2Gi
  workerGroupSpecs:
    - replicas: 2
      minReplicas: 2
      maxReplicas: 2
      groupName: small-group
      rayStartParams:
        block: "true"
      template:
        spec:
          containers:
            - name: ray-worker
              image: quay.io/modh/ray@sha256:0d715f92570a2997381b7cafc0e224cfa25323f18b9545acfd23bc2b71576d06
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "1"
                  memory: 2Gi
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: sdk-configurations
  namespace: raytest
spec:
  rayVersion: "2.47.1"
  headGroupSpec:
    rayStartParams:
      dashboard-host: "0.0.0.0"
      block: "true"
    template:
      spec:
        containers:
          - name: ray-head
            image: quay.io/modh/ray@sha256:0d715f92570a2997381b7cafc0e224cfa25323f18b9545acfd23bc2b71576d06
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
              requests:
                cpu: "1"
                memory: 2Gi
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 1
      groupName: small-group
      rayStartParams:
        block: "true"
      template:
        spec:
          containers:
            - name: ray-worker
              image: quay.io/modh/ray@sha256:0d715f92570a2997381b7cafc0e224cfa25323f18b9545acfd23bc2b71576d06
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "1"
                  memory: 2Gi
